server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yang-Athin/springcloud.git
          search-paths: config
          username: Yang-Athin
          password: 19961205yuan
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/